### ISSUE TITLE
Install button not showing

### ISSUE THREAD

**Issue by Blueric** [pwa-builder/pwa-install#258] opened 2020-04-22 16:00 UTC
I was checking out the component and noticed that the install button is not showing when opening  pwainstall.glitch.me. I tried in Edge Chromium, Chrome, and Edge (non-chromium). 

![Annotation 2020-04-22 095915](https://user-images.githubusercontent.com/16259907/80004751-f4250000-847f-11ea-8498-af31a9aebb33.png)

**Comment by Blueric** [comment] 2020-04-22 16:05
WTF?! I swear the button wasn't there. Somehow, the process of using the snip tool to grab a screen shot of Chrome caused it to show up. I thought I was crazy, so I tested it again using Edge Chromium. I confirmed the button was missing and then opened Snip. But as soon as I snipped the image, it suddenly showed up, and was in the screen shot.

**Comment by Blueric** [comment] 2020-04-22 17:19
OK, I was able to reproduce it again. Opening an InPrivate browser session in Chrome resulted in the button not showing. Here's a screens hot, including dev tools opened up showing the #shadow-root

![Annotation 2020-04-22 111734](https://user-images.githubusercontent.com/16259907/80012734-fe98c700-848a-11ea-9b0d-7387cb825040.png)

**Comment by Blueric** [comment] 2020-04-22 17:24
Console shows these issues when the button fails to load. I'm completely new to the PWA scene, and just trying to get up to speed, so I don't know enough to know if this is an issue with glith.me or with the component it self.

[PWA Builder] Network request failed and no cache.TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode

The FetchEvent for "https://pwainstall.glitch.me/" resulted in a network error response: an object that was not a Response was passed to respondWith().

**Comment by jgw96** [comment] 2020-04-22 18:09
Hello, thanks for opening an issue with us! @Blueric I am not able to reproduce this outside of an inprivate Edge tab , are you able to confirm that it works for you outside of inprivate?

**Comment by jgw96** [comment] 2020-04-22 18:14
Figured out why its not working in inprivate mode. That error you got was from a service worker request being blocked. Just so we dont confuse users because of the console errors that pop up there, i simplified the service worker in the demo. Turns out, that is expected behavior for inprivate, the event for installing also will not fire in an inprivate tab. @Blueric I just wanted to confirm, are you still having this issue outside of inprivate?

**Comment by Blueric** [comment] 2020-04-22 19:48
I have been playing with it some more, and (mostly) figured out what was going on. For the most part, it's due to my ignorance on service workers. I spent the last hour playing with PWABuilder, deployed a starter app to my server, confirmed it all works as expected, and learned some things in the process.

The first issue is that I wasn't opening the page via HTTPS. The install button doesn't show up in that case, because the service worker isn't registered. 

The second issue is I was using In-private, which also doesn't seem to work as you pointed out.

I still can't explain why the button didn't show up at first, and then later appeared, as if it was just really delayed. I can't duplicate this now, even if I unregister the service worker, clear cache, and reload it.

I am still not able to get it to work in Edge (non-chromium). It shows "Install" without any button styling and lists an error on the console. **Unable to get property 'define' of undefined or null reference**. My understanding is that it _should_ work, but I'm not too worried about it, given Edge chromium works. 

I get all the same behavior on my test app at https://test.tournamenttiger.com, which is just the sample app from https://github.com/pwa-builder/pwa-starter

@jgw96 Thanks for the quick follow up.

**Comment by jgw96** [comment] 2020-04-22 22:19
Cool! No worries at all, we are all still learning! I'm not sure exactly, but I'm guessing it might have been delayed for you that first time because the event that we get from the browser that we can trigger install off of just hadn't fired yet for you. Feel free to open another issue though if you see that again. As far as Edge Classic goes, we actually don't officially support that browser with this component! We do however support the new chromium based Edge (: Based on all of this, I am going to close this issue for now, thank you!

**Closed** 2020-04-22 22:19 UTC
Labels: needs attention :wave:, question :grey_question:
