### ISSUE TITLE
isIOS type

### ISSUE THREAD

**Issue by Mister-Hope** [pwa-builder/pwa-install#457] opened 2020-10-24 08:06 UTC
https://github.com/pwa-builder/pwa-install/blob/d5fabc828864df8a2712c485793bfa1a18b1798b/src/pwa-install.ts#L21

https://github.com/pwa-builder/pwa-install/blob/d5fabc828864df8a2712c485793bfa1a18b1798b/src/pwa-install.ts#L596-L601

Typescript will type maxTouchPoints as number, so it will think iOS can be any number less than 1(Though it can't)

It will give me errors when I import the ts file.

---

BTW: The reason I am importing it is that you are missing `"types"` in package.json while not placing types declaration files in npm package, so I am not able to use it in typescript env directly. So I also suggest adding `d.ts` files in the next release.

(It's another feature request)

😘

**Comment by lee-leonardo** [comment] 2020-10-27 21:34
Just to clarify this ask:

From my understanding, the issue is that the value of isIOS is returning a number value hence a type mismatch. This is because of the short circuit that is being used within the logic, this is a bug, I'll fix it.

I am assuming as well that you have your tsconfig to be set to strict mode, which is why you are seeing this issue.

From what I gather `maxTouchPoints` is 0 my computer browsers and since this isn't a WebKit specific feature meaning it follows W3C standards, we are to write the logic so that it works for all browsers.

I'll make the changes so that this component can be used in strict mode. I'm not convinced we need to create a declaration file for a single component. The component's values should be inferred with a module import. We use this component in our applications and include it in the starter app and we've not encountered a scenario where the types haven't shown up.

**Comment by Mister-Hope** [comment] 2020-10-28 03:48
You will need a type if you are using a dynamic import by using the import function, which the website provides.

 I'm currently using this on view press and view price is doing server side rendering to generate html files  More than a spa for search engines.

 I'm not sure, but I seemed to trigger some issues on server side rendering when jobs importing it in my entrance file.  I'm not just copying the source code and improve it in my code intead of importing it.

**Comment by jgw96** [comment] 2020-10-28 18:12
Hey @Mister-Hope , unfortunately this use case (of trying to use the typescript files directly to use the component) is not a supported scenario, and as you have run into, its going to cause issues. This component is packaged as a standalone NPM package and is meant to be either installed from NPM as any other NPM package https://www.npmjs.com/package/@pwabuilder/pwainstall#npm or through a script tag https://www.npmjs.com/package/@pwabuilder/pwainstall#script-tag . Because this is not a supported scenario I am going to close this issue for now as a wontfix. However, I am going to open an issue for the strict mode fixes that @lee-leonardo mentioned as we should update the component to be strict mode compatible. Thanks for using PWABuilder!

**Closed by jgw96** 2020-10-28 18:12 UTC
Labels: bug :bug:, needs attention :wave:
